spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hookingdb.c9diwssl1oou.ap-northeast-2.rds.amazonaws.com:3306/${DB_TABLE}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            redirect-uri: ${KAKAO_REDIRECT_URL}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      generate-ddl: true
      format_sql: true
      use_sql_comments: true
  session:
    store-type: jdbc
  jwt:
    secretKey: ${SECRET_KEY}
    blacklist:
      access-token: BlackList_AccessToken_
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379

#  jackson:
#    serialization:
#      fail-on-empty-beans: false

app:
  deployment:
    url: ${request_URL}
    processor:
      url: ${redirect_URL}


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false